# Location of top-level MicroPython directory
MPY_DIR = ../../../waspOS/wasp-os/micropython

# Name of module
MOD = wrap

# Source files (.c or .py)
SRC = features1.c wrapApp.py

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = armv7m

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
