# MPY_DIR = ../../wasp-os/micropython
MPY_DIR = ../../../waspOS/wasp-os/micropython
MOD = wrap
SRC = handler.c externApp.c compat.py.c wrapApp.py
# SRC = external.old.cpp wrapper.old.cpp
# SRC = external.old.c wrapper.old.c
ARCH = armv7m
include $(MPY_DIR)/py/dynruntime.mk
