# MPY_DIR = ../../wasp-os/micropython
MPY_DIR = ../../../waspOS/wasp-os/micropython
MOD = wrap
SRC = wrapApp.py
# SRC = handler.cpp externApp.cpp compat.py.cpp wrapApp.py
ARCH = armv7m
include $(MPY_DIR)/py/dynruntime.mk
