MPY_DIR = ../../wasp-os/micropython
MOD = wrap
SRC = handler.cpp externApp.cpp compat.py.cpp wrapApp.py
# SRC = external.old.cpp wrapper.old.cpp
# SRC = external.old.c wrapper.old.c
ARCH = armv7m
include $(MPY_DIR)/py/dynruntime.mk
